Проверь, там где-то допущена ошибка При переходе в этот билд открывается пустая страница
pp-min-2.js:1 Error handler not initialized: page is not in an iframe
client:745 WebSocket connection to 'wss://preview--webapp-creation-project.poehali.dev/?token=Xq75XO_smeXN' failed: 
createConnection @ client:745
FirstLoginPasswordModal.tsx:1  Failed to load resource: the server responded with a status of 500 ()
ProfileSettings.tsx:1  Failed to load resource: the server responded with a status of 500 ()
(index):1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
client:755 WebSocket connection to 'wss://localhost:5173/?token=Xq75XO_smeXN' failed: 
createConnection @ client:755
telemetry-min.js:1 [vite] failed to connect to websocket.
your current setup:
  (browser) preview--webapp-creation-project.poehali.dev/ <--[HTTP]--> localhost:5173/ (server)
  (browser) preview--webapp-creation-project.poehali.dev:/ <--[WebSocket (failing)]--> localhost:5173/ (server)
Check out your Vite / network configuration and https://vite.dev/config/server-options.html#server-hmr .
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
connect @ client:765
await in connect
connect @ client:289
connect @ client:373
(anonymous) @ client:823

Вот логи