Найди решение этой проблемы
pp-min-2.js:1 Error handler not initialized: page is not in an iframe
pp-min-2.js:1 Access to XMLHttpRequest at 'https://api.poehali.dev/api/project/badge/displayed?project_name=webapp-creation-project' from origin 'https://techsale-b2b.ru' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
_0x1567ac @ pp-min-2.js:1
pp-min-2.js:1  GET https://api.poehali.dev/api/project/badge/displayed?project_name=webapp-creation-project net::ERR_FAILED 200 (OK)
_0x1567ac @ pp-min-2.js:1
team:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
telemetry-min.js:1  POST https://functions.poehali.dev/9f41e955-72a6-447c-aaae-4b5ea1b0c30a 500 (Internal Server Error)
(anonymous) @ telemetry-min.js:1
y @ index-BrED8BSK.js:27
Qe @ index-BrED8BSK.js:5
it @ index-BrED8BSK.js:5
at @ index-BrED8BSK.js:5
_i @ index-BrED8BSK.js:5
vi @ index-BrED8BSK.js:5
(anonymous) @ index-BrED8BSK.js:5
Ul @ index-BrED8BSK.js:8
Je @ index-BrED8BSK.js:5
Ci @ index-BrED8BSK.js:5
gn @ index-BrED8BSK.js:5
mn @ index-BrED8BSK.js:5

Проблема не решилась 
Менеджер по прежнему не создается 

Задача: 
Найди решение и сделай оптимальную реализацию для добавления менеджера и других ролей через owner